blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/htmlstreamofficial/preline-dev/issues/new?template=bug_report.yml
    about: Use this template to report a bug.
